In [162]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import NearestNeighbors



In [73]:
df=pd.read_csv("anime.csv")

In [74]:
df

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12289    4.15      211  
12290    4.28      183  
12291    4.88      219  
12292    4.98      175  
12293    5.46      142  

[12294 rows x 7 columns]

In [75]:
df.isna().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [76]:
df.describe()

anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12294 non-null  int64  
 1   name      12294 non-null  object 
 2   genre     12232 non-null  object 
 3   type      12269 non-null  object 
 4   episodes  12294 non-null  object 
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB


In [78]:
df['type'] = df['type'].fillna('None')
df['genre'] = df['genre'].fillna('None')
df['rating'] = df['rating'].fillna(df['rating'].median())
episode_ = df['episodes'].replace('Unknown', np.nan)
# episode_ = episode_.fillna(episode_.median())


In [79]:
df.isna().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [80]:
df

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre   type episodes  \
0                   Drama, Romance, School, Supernatural  Movie        1   
1      Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64   
2      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
3                                       Sci-Fi, Thriller     TV       24   
4      Action, Comedy, Historical, Parody, Samurai, S...     TV       51   
...                                                  ...    ...      ...   
12289                                             Hentai    OVA        1   
12290                                             Hentai    OVA        1   
12291                                             Hentai    OVA        4   
12292                                             Hentai    OVA        1   
12293                                             Hentai  Movie        1   

       rating  members  
0        9.37   200630  
1        9.26   793665  
2        9.25   114262  
3        9.17   673572  
4        9.16   151266  
...       ...      ...  
12289    4.15      211  
12290    4.28      183  
12291    4.88      219  
12292    4.98      175  
12293    5.46      142  

[12294 rows x 7 columns]

# Feature Extraction

In [91]:
type_ = pd.get_dummies(df['type'])
genre_ = df['genre'].str.get_dummies(sep=',')
genre_.head()

Adventure   Cars   Comedy   Dementia   Demons   Drama   Ecchi   Fantasy  \
0           0      0        0          0        0       0       0         0   
1           1      0        0          0        0       1       0         1   
2           0      0        1          0        0       0       0         0   
3           0      0        0          0        0       0       0         0   
4           0      0        1          0        0       0       0         0   

    Game   Harem  ...  Shoujo  Shounen  Slice of Life  Space  Sports  \
0      0       0  ...       0        0              0      0       0   
1      0       0  ...       0        0              0      0       0   
2      0       0  ...       0        0              0      0       0   
3      0       0  ...       0        0              0      0       0   
4      0       0  ...       0        0              0      0       0   

   Super Power  Supernatural  Thriller  Vampire  Yaoi  
0            0             0         0        0     0  
1            0             0         0        0     0  
2            0             0         0        0     0  
3            0             0         0        0     0  
4            0             0         0        0     0  

[5 rows x 83 columns]

In [12]:
#Due to dummy coding, we can see above that the second anime is (at least) an Adventure/Drama/Fantasy type.

In [93]:
X = pd.concat([genre_, type_, episode_, df['rating'], df['members']],axis=1)
X.head()

Adventure   Cars   Comedy   Dementia   Demons   Drama   Ecchi   Fantasy  \
0           0      0        0          0        0       0       0         0   
1           1      0        0          0        0       1       0         1   
2           0      0        1          0        0       0       0         0   
3           0      0        0          0        0       0       0         0   
4           0      0        1          0        0       0       0         0   

    Game   Harem  ...  Movie  Music   None    ONA    OVA  Special     TV  \
0      0       0  ...   True  False  False  False  False    False  False   
1      0       0  ...  False  False  False  False  False    False   True   
2      0       0  ...  False  False  False  False  False    False   True   
3      0       0  ...  False  False  False  False  False    False   True   
4      0       0  ...  False  False  False  False  False    False   True   

   episodes  rating  members  
0         1    9.37   200630  
1        64    9.26   793665  
2        51    9.25   114262  
3        24    9.17   673572  
4        51    9.16   151266  

[5 rows x 93 columns]

In [14]:
#Notice that 'episodes' and 'members' columns contain values much larger than the rest of the dataset, so let's scale our features.

In [95]:
from sklearn.preprocessing import MinMaxScaler
scaled = MinMaxScaler()
X = scaled.fit_transform(X)
X

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 9.24369748e-01, 1.97872202e-01],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.46725371e-02, 9.11164466e-01, 7.82770102e-01],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        2.75178866e-02, 9.09963986e-01, 1.12689267e-01],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.65107320e-03, 3.85354142e-01, 2.11063682e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 3.97358944e-01, 1.67667411e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 4.54981993e-01, 1.35120208e-04]])

# Recommendation System

In [97]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation


In [18]:
# User similarity - pairwise - taking 2 rows at a time it will compute distance
# That distance is scaled between 0 to 1
# Suppose distance between 2 rows is 0.  We want similarity, not a distance.
# That is calculated as Similarity=1-distance. So 1-0=1. i.e. similarity in rows is 1.
# Suppose distance is 0.9. So 1-0.9=0.1
user_sim = 1 - pairwise_distances(genre_.values,metric='cosine')

In [19]:
user_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.28571429, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.28571429, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ]])

#this is similarity matrix as diagonal values are 1

In [21]:
np.fill_diagonal(user_sim, 0)
user_sim

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.28571429, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.28571429, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.        ]])

In [22]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_sim)
user_sim_df

0         1         2      3         4         5         6      \
0        0.0  0.000000  0.000000    0.0  0.000000  0.223607  0.000000   
1        0.0  0.000000  0.285714    0.0  0.285714  0.338062  0.566947   
2        0.0  0.285714  0.000000    0.0  1.000000  0.169031  0.377964   
3        0.0  0.000000  0.000000    0.0  0.000000  0.000000  0.000000   
4        0.0  0.285714  1.000000    0.0  0.000000  0.169031  0.377964   
...      ...       ...       ...    ...       ...       ...       ...   
12289    0.0  0.000000  0.000000    0.0  0.000000  0.000000  0.000000   
12290    0.0  0.000000  0.000000    0.0  0.000000  0.000000  0.000000   
12291    0.0  0.000000  0.000000    0.0  0.000000  0.000000  0.000000   
12292    0.0  0.000000  0.000000    0.0  0.000000  0.000000  0.000000   
12293    0.0  0.000000  0.000000    0.0  0.000000  0.000000  0.000000   

          7         8         9      ...  12284     12285  12286  12287  \
0      0.250000  0.000000  0.000000  ...    0.0  0.288675    0.0    0.0   
1      0.188982  0.285714  0.285714  ...    0.0  0.000000    0.0    0.0   
2      0.188982  1.000000  1.000000  ...    0.0  0.000000    0.0    0.0   
3      0.000000  0.000000  0.000000  ...    0.0  0.000000    0.0    0.0   
4      0.188982  1.000000  1.000000  ...    0.0  0.000000    0.0    0.0   
...         ...       ...       ...  ...    ...       ...    ...    ...   
12289  0.000000  0.000000  0.000000  ...    1.0  0.000000    1.0    1.0   
12290  0.000000  0.000000  0.000000  ...    1.0  0.000000    1.0    1.0   
12291  0.000000  0.000000  0.000000  ...    1.0  0.000000    1.0    1.0   
12292  0.000000  0.000000  0.000000  ...    1.0  0.000000    1.0    1.0   
12293  0.000000  0.000000  0.000000  ...    1.0  0.000000    1.0    1.0   

       12288  12289  12290  12291  12292  12293  
0        0.0    0.0    0.0    0.0    0.0    0.0  
1        0.0    0.0    0.0    0.0    0.0    0.0  
2        0.0    0.0    0.0    0.0    0.0    0.0  
3        0.0    0.0    0.0    0.0    0.0    0.0  
4        0.0    0.0    0.0    0.0    0.0    0.0  
...      ...    ...    ...    ...    ...    ...  
12289    1.0    0.0    1.0    1.0    1.0    1.0  
12290    1.0    1.0    0.0    1.0    1.0    1.0  
12291    1.0    1.0    1.0    0.0    1.0    1.0  
12292    1.0    1.0    1.0    1.0    0.0    1.0  
12293    1.0    1.0    1.0    1.0    1.0    0.0  

[12294 rows x 12294 columns]

In [23]:
# idxmax() method returns a Series with the index of the maximum value for each column. (row 3 anc col 11 has highest value as 1)
# By specifying the column axis (axis='columns' or 1), the idxmax() method returns a Series with the index of the maximum value for each row.

user_sim_df.idxmax(axis=1)

0         5805
1          200
2            4
3           59
4            2
         ...  
12289    11114
12290    11114
12291    11114
12292    11114
12293    11114
Length: 12294, dtype: int64

In [24]:
user_sim_df.iloc[0:5, 0:5]

0         1         2    3         4
0  0.0  0.000000  0.000000  0.0  0.000000
1  0.0  0.000000  0.285714  0.0  0.285714
2  0.0  0.285714  0.000000  0.0  1.000000
3  0.0  0.000000  0.000000  0.0  0.000000
4  0.0  0.285714  1.000000  0.0  0.000000

# Training and testing of the data

In [99]:
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [121]:
x= df.drop(['genre'],axis=1).values
y = df['genre'].values
X_train,X_test,Y_train,Y_test = train_test_split(x,y,random_state=0)

In [123]:
x

array([[32281, 'Kimi no Na wa.', 'Movie', '1', 9.37, 200630],
       [5114, 'Fullmetal Alchemist: Brotherhood', 'TV', '64', 9.26,
        793665],
       [28977, 'Gintama°', 'TV', '51', 9.25, 114262],
       ...,
       [5621, 'Violence Gekiga David no Hoshi', 'OVA', '4', 4.88, 219],
       [6133, 'Violence Gekiga Shin David no Hoshi: Inma Densetsu',
        'OVA', '1', 4.98, 175],
       [26081, 'Yasuji no Pornorama: Yacchimae!!', 'Movie', '1', 5.46,
        142]], dtype=object)

In [125]:
y

array(['Drama, Romance, School, Supernatural',
       'Action, Adventure, Drama, Fantasy, Magic, Military, Shounen',
       'Action, Comedy, Historical, Parody, Samurai, Sci-Fi, Shounen',
       ..., 'Hentai', 'Hentai', 'Hentai'], dtype=object)

In [127]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3,random_state=10)

In [129]:
X_train

array([[1639, 'Boku no Pico', 'OVA', '1', 5.13, 57355],
       [31927, 'Phantom of the Kill: Zero kara no Hangyaku', 'Movie',
        '1', 6.39, 4893],
       [10516, 'Anemone', 'OVA', '1', 6.69, 2466],
       ...,
       [5854, 'Shin Chou Kyou Ryo: Condor Hero III', 'TV', '26', 7.58,
        1377],
       [4827, '_Summer Specials', 'Special', '2', 5.57, 1977],
       [16287, 'One Piece: Romance Dawn', 'OVA', '1', 7.6, 8326]],
      dtype=object)

Conclusion:

Now these anime are much closer in similarity to Death Note. The reason our method described above did not return the most optimum results is due greatly to the fact that we ignored the rating.csv dataset. This dataset is essentially user preference data - if users have seen and enjoyed Death Note, what else are they inclined to like?